#pragma once
#include "../../NetVars/NetVars.h"

#include "AnimState/TFPlayerAnimState.h" //includes class C_BaseCombatWeapon

class C_BaseEntity
{
public:
	bool IsFeignDeathReady();
	float GetStepSize();
	float GetConveyorSpeed();
	C_BaseEntity *GetGroundEntity();
	const char* szGetClass();
	const char* GetModelName();
	void RemoveEffect(byte Effect);
	void SetGlowEnabled(bool bState);
	void SetFov(int nFov);
	void ForceTauntCam(bool bState);
	void SetEyeAngles(const Vec3& v);
	void RemoveCond(int cond);
	void SetFlags(int nFlags);
	void SetCond(int cond);
	void SetTickBase(int n);
	void SetRenderAngles(const Vec3& v);
	void SetAbsOrigin(const Vec3& v);
	void SetAbsAngles(const Vec3& v);
	void SetCurrentCmd(C_UserCmd* cmd);
	void SetVecOrigin(Vec3& vOrigin);
	void GetRenderBounds(Vec3& vMins, Vec3& vMaxs);
	void UpdateGlowEffect();
	void UpTickBase();
	void UpdateClientSideAnimation();
	void IncreaseTickBase();
	void* GetThrower();
	int DrawModel(int flags);
	int GetCond();
	int GetCondEx();
	int GetCondEx2();
	int GetClassId();
	int GetClassNum();
	int GetMaxHealth();
	int GetHealth();
	int GetTeamNum();
	int GetFlags();
	int GetIndex();
	int GetOwner();
	int GetAmmo();
	int GetHitboxSet();
	int GetTickBase();
	int GetState();
	int GetType();
	int GetNumOfHitboxes();
	int GetFov();
	int GetObserverTarget();
	int GetObserverMode();
	float GetSurfaceFriction();
	float GetMaxSpeed();
	float GetWaterJumpTime();
	float GetDamageRadius();
	float flSimulationTime();
	float GetNextAttack();
	const Vec3& GetRenderAngles();
	const Vec3& GetAbsOrigin();
	const Vec3& GetAbsAngles();
	Vec3 GetViewOffset();
	Vec3 GetEyePosition();
	Vec3 GetVecOrigin();
	Vec3 GetShootPos();
	Vec3 GetWorldSpaceCenter();
	Vec3 GetHitboxPos(int nHitbox);
	Vec3 GetBonePos(int nBone);
	Vec3 GetCollideableMins();
	Vec3 GetCollideableMaxs();
	Vec3 GetVelocity();
	Vec3 GetEyeAngles();
	Vec3 GetPunchAngles();
	BYTE GetLifeState();
	byte GetWaterLevel();
	C_BaseEntity *FirstMoveChild();
	C_BaseEntity *NextMovePeer();
	C_ClientClass* GetClientClass();
	MoveType_t GetMoveType();
	C_BaseCombatWeapon* GetActiveWeapon();
	C_UserCmd *GetCurrentCommand();
	model_t *GetModel();
	matrix3x4 &GetRgflCoordinateFrame();
	CTFPlayerAnimState* GetAnimState();
	std::array<float, MAXSTUDIOPOSEPARAM> GetPoseParam();
	bool GetHitboxMinsAndMaxsAndMatrix(int nHitbox, Vec3& mins, Vec3& maxs, matrix3x4& matrix, Vec3* center);
	bool GetHitboxMinsAndMaxs(int nHitbox, Vec3& mins, Vec3& maxs, Vec3* center);
	bool IsPlayerOnSteamFriendList(C_BaseEntity* pEntity);
	bool SetupBones(matrix3x4* pBoneToWorldOut, int nMaxBones, int nBoneMask, float fCurrentTime);
	bool IsSlowed();
	bool IsBaseCombatWeapon();
	bool IsWearable();
	bool IsSentrygun();
	bool IsTeleporter();
	bool IsDispenser();
	bool IsInValidTeam();
	bool GetTouched();
	bool IsStunned();
	bool IsDormant();
	bool IsOnGround();
	bool IsInWater();
	bool IsSwimming();
	bool IsGlowEnabled();
	bool IsAlive();
	bool IsVulnerable();
	bool IsCritBoosted();
	bool IsPlayer();
	bool IsBuilding();
	bool IsPickup();
	bool IsScoped();
	bool IsTaunting();
	bool IsDucking();
	bool IsUbered();
	bool IsBonked();
	bool IsCloaked();
};